name: Deploy Shiny App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code (with LFS)
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

    - name: Install R packages
      run: |
        R -e 'install.packages(c(
          "rsconnect","shiny","tidyverse","lubridate","ggplot2","DT","png","ggiraph",
          "RColorBrewer","readr","shinyWidgets","shinymanager","formattable","writexl",
          "WriteXLS","rpivotTable","htmlwidgets","shinyjs","clipr","rvest",
          "shinydashboard","ggrepel","readxl","plotly","shinyalert"
        ))'

    - name: Configure shinyapps.io
      env:
        SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
        SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
      run: |
        R -e 'rsconnect::setAccountInfo(
                name   = "bassemurm",
                token  = Sys.getenv("SHINYAPPS_TOKEN"),
                secret = Sys.getenv("SHINYAPPS_SECRET")
              )'

  
    - name: Deploy to shinyapps.io
      run: |
        R -e 'rsconnect::deployApp(
          appDir  = ".",
          appName = "benin-select-2024",
          account = "bassemurm"
        )'

		
